import Head from 'next/head';
import { getSession } from 'next-auth/client';
import React from 'react';
import { useTranslations } from 'next-intl';
import { ListOrders } from '../../components/orders';

// import { showFormSelector } from '../../redux/chatbot/selectors';
// import { setEmptyFormAction, showFormAction } from '../../redux/chatbot';

export default function Index({ session, locale }: { session: any; locale: string }) {
    if (!session) return <></>;
    const t = useTranslations();

    return (
        <>
            <Head>
                <title>LiveProshop - Orders</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/logo-1.svg" />
            </Head>

            <div className="block-white-8 mr-10 white-shadow-big">
                <div className="page-title">
                    <h1>{t('Orders')}</h1>
                </div>
                <div
                    className="text-gray-400 hidden"
                    dangerouslySetInnerHTML={{
                        __html: t('orders_descr')
                    }}
                />
            </div>
            <div className="block-white-8 mr-10 white-shadow-medium mt-10">
                <ListOrders locale={locale} />
            </div>
        </>
    );
}
export async function getServerSideProps(context: any) {
    const { locale } = context;
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: { destination: `/${locale === 'fr' ? '' : `${locale}/`}auth/signin` }
        };
    }

    return {
        props: {
            session,
            locale,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
