import Head from 'next/head';
import { getAllPages, getPageData } from '../../lib/pages';
import fs from 'fs';
import path from 'path';
import FullLayout from '../../components/layout/FullLayout';
import React from 'react';

const postsDirectory = path.join(process.cwd(), '/pages/pages/data');

export default function Page({ pageData }) {
    console.log(pageData[0].slug);
    return (
        <>
            <Head>
                <title>LiveProshop</title>
                {/*<meta name="description" content="Generated by create next app" />*/}
            </Head>
            <div className="flex">
                <div className="w-full">
                    <h1 className="page-heading text-center">Frequently asked questions</h1>
                </div>
            </div>
            {/*<div className="flex justify-center">*/}
            {/*    <div*/}
            {/*        className="container bg-white rounded-lg flex flex-wrap*/}
            {/*        pt-4 pb-10 m-auto mt-6 md:mt-15 lg:px-12 xl:px-16">*/}
            {/*        <div*/}
            {/*            className="w-full max-w-full"*/}
            {/*            dangerouslySetInnerHTML={{ __html: pageData[0].content }}*/}
            {/*        />*/}
            {/*    </div>*/}
            {/*</div>*/}
        </>
    );
}
Page.Layout = FullLayout;

export async function getStaticPaths() {
    const paths = await getAllPages();
    return {
        paths,
        fallback: false
    };
}

export async function getStaticProps({ params, locale }) {
    const pageData = await getPageData(params.slug);
    const fullPath = path.join(postsDirectory, `${params.slug}.html`);
    pageData[0].content = fs.readFileSync(fullPath, 'utf8');
    pageData[0].slug = params.slug;
    return {
        props: {
            pageData,
            messages: {
                ...require(`../../messages/${locale}.json`)
            }
        }
    };
}
